loom.platform=fabric

# Global
deps.yarn_build=1
deps.compat=\
    controlify=5q2runiM
deps.compat_runtime=

# Fabric
deps.fapi=0.133.13+1.21.9
deps.modmenu=15.0.0-beta.3
deps.yacl=3.8.0+1.21.9
deps.cicada=0.14.2+1.21.6-and-above

# Mod
mod.mc_dep=>=1.21.8 <=1.21.9
mod.mc_title=1.21.9
mod.mc_targets=1.21.9